name: CI - Run Automation Tests

on:
  push:        # Run when you push code
    branches: [ "**" ]
  pull_request: # Run when someone opens a PR into main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Official Playwright Action - installs browsers & caches them
      - name: Install Playwright Browsers
        uses: microsoft/playwright-github-action@v1

      # Run tests
      - name: Run tests
        run: |
          pytest -v